### ISSUE TITLE
Updated Production Code

### ISSUE THREAD

**Issue by romarionelson** [hres/fcdr#11]
Hi Anthony, 

Hi have updated the production code, can you pull it so that it's reflected on the application? Additionally, I have added a column and changed the datatype of column Password to the Users table and I will need those as well to be reflected on the prod database. I will try to contact you to discuss a little more on the latter change

**Comment by ayoung8** [comment]
Code pulled
Db refreshed.

**Comment by romarionelson** [comment]
Thank you!
