### ISSUE TITLE
Failing to create records in prod DB

### ISSUE THREAD

**Issue by romarionelson** [hres/fcdr#12]
Hi Anthony, 
We tried inserting records in the database through the Create and import functionalities son https://sodium-monitoring.hres.ca/login.php but we where not able too. Meanwhile, we tried doing the same in dev and it worked.  I spent some time debugging the code, and it looks like the problem is that the application doesn't have permission to writes in some of the tables. 

Can you please see why the application is being denied from writing to some of the tables?

**Comment by ayoung8** [comment]
cleaned up permissions try now?

**Comment by romarionelson** [comment]
It gives a new error now: Connection failed: Access denied for user 'fcdrproduser'@'192.168.177.18' (using password: YES)

**Comment by ayoung8** [comment]
database recreated after modifying the trigger.

**Comment by romarionelson** [comment]
Great thanks but I think the only thing missing now is that it's possible that the user table and possibly the reference tables empty. 
Among the scripts you sent last Friday, did you also run fcdr_user.sql and fcdr_data.sql when you recreated the database? If not please do so. Furthermore,  I have updated the readme as you suggested with instruction regarding the DB creation

**Comment by romarionelson** [comment]
Resolved
