### ISSUE TITLE
New Host 

### ISSUE THREAD

**Issue by romarionelson** [hres/fcdr#3]
Hi Anthony,

I just created a new branch called "Maintenance-Release-1". Could you host that branch (with it's own Mysql Server)? That's the branch we'll use for future QA.

Please let me know if you have any questions.

**Comment by ayoung8** [comment]
Complete

**Comment by romarionelson** [comment]
Thank you but it doesn't seem to be connected to MySQL because  I get the following error message when attempting to login: "Connection failed: Connection refused". Can you look into it? Thanks
