### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by romarionelson** [hres/fcdr#4]
Hi Anthony, 
IT Security ran a vulnerability test on the Application and provided us a report containing all the issues and potential solutions to solve them . Among those issues, several of them can be solved by adding some headers on the server side. 

These are all the missing header flagged by the IT security:  

Missing "Content-Security-Policy" header 
Missing "X-Content-Type-Options" header 
Missing "X-XSS-Protection" header
"X-Frame-Options" header
Missing HTTP Strict-Transport-Security Header

Missing HTTP Strict-Transport-Security Header. 

I thing those headers should be added in the nginx.conf. Here is a link that might help you 
https://gist.github.com/plentz/6737338 

So configuring the server to use those headers will solve those issues. 

Also I have a "Missing Secure Attribute in Encrypted Session (SSL)" Cookie Issue  and this can be solved by setting the session.cookie_secure to true in the php.ini file (**session.cookie_secure = True**)

Please let me know if you have any questions. Thanks

**Comment by ayoung8** [comment]
Forgot to update this.
Most are false positives but did add in several additional security items that were not in the list:
nosniff
1; mode=block
SAMEORIGIN
session.cookie_httponly
