### ISSUE TITLE
Create Repositories for Sodium Monitoring  refactoring 

### ISSUE THREAD

**Issue by romarionelson** [hres/fcdr#5]
Hi Anthony, 

So we  are in the process of refactoring the sodium monitoring application and we will need  2 new repositories for that . One will be to build the  Rest services (let's call this **fcdr-task-service**) and the other will be use to build the web interface (**fcdr-webapp**). 

Once those repositories are, we'll update their README files with the technology stack we'll be using and the instructions on how to install them. 
Please let me know if you have any question.

Thanks

**Comment by ayoung8** [comment]
No action taken per Michele and Colette
Issue not closed per Colette 
Unassigning myself
