### ISSUE TITLE
sodium monitoring branch

### ISSUE THREAD

**Issue by ayoung8** [hres/fcdr#7]
Tried a couple times to deploy the sodium monitoring branch over thanksgiving weekend.
It kept on failing
Looking at the code, it seems the connection.php is not referring to the /etc/sodium-monitoring/xxx as suggested in the readme.
Deployment halted until code updated

**Comment by ayoung8** [comment]
Also if this is the final deployment branch its probably a good idea to bring the commits in line, current it shows 5 behind the master and 3 ahead of the master.

**Comment by romarionelson** [comment]
Hi Anthony, ops, I thought I did it on Thursday  but I have now fixed it so it should now be fine. Thanks

**Comment by romarionelson** [comment]
Hi Anthony, 
Can you please confirm the URL where we can expect the application to be deployed? I currently have the following in my records: sodium-monitoring.hres.ca.

**Comment by ayoung8** [comment]
sodium-monitoring.hres.ca/login.php is now available 
Please close issue if resolved

**Comment by romarionelson** [comment]
Hi Anthony! Following the the discussion we just had over the phone, I made the requested changes to the development (master) branch, and was able to log in. On the production branch, however, I wasn't still able to log in even though I used the same credentials. Following is the message I keep getting: 

Connection failed: Access denied for user 'fcdruseer// DB username'@'192.168.177.18' (using password: YES). 

Could you look into this? Thank you.
